name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  # check-bats-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
  echoecho:
    runs-on: ubuntu-18.04
    steps:
      - name: Test met zonder pipe teken
        env:
          BLA: Dit is geblaat
        run: echo "$BLA zonder pipe teken."
      - name: Nu met een pipe teken.
        run: |
          echo "$BLA met een pipe teken"